name: dbt core cli

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: python -m pip install --upgrade pip
        
    - name: Install DBT core
      run: pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery dbt-trino
    - name: setup dbt project
      run: |
        ./dbt/core/cli.sh initSilently CI
        cd CI
        ./dbt/core/cli.sh initBQ
    
